services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      database:
        condition: service_healthy
        restart: true
      ollama:
        condition: service_started

  database:
    image: pgvector/pgvector:pg18-trixie
    restart: always
    environment:
      POSTGRES_DB: second-mind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database/schema:/docker-entrypoint-initdb.d
    secrets:
      - db_password

  ollama:
    image: ollama/ollama:latest
    container_name: second-mind-ollama
    tty: true
    restart: unless-stopped
    networks:
      - llm-network
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]

networks:
  llm-network:
    driver: bridge

secrets:
  db_password:
    file: database/db_password.txt

volumes:
  postgres_data: